#!/bin/sh
# See how we were called.
case "$1" in
  start)
        # Start daemons.
        echo -n "Starting named: "
        /usr/sbin/named -4 -c /etc/named.conf
        echo
        ;;
  *)
        echo "Usage: named start"
        exit 1
esac

exit 0
