#!/bin/sh
if [ ! -d /etc/bind ];then
	cp -R -p /data/bind /etc/.
	chown root:named /etc/bind
	rm /etc/bind/rndc.key
fi
/usr/bin/perl /opt/webmin/miniserv.pl /etc/webmin/miniserv.conf
if [ $? != 0 ];then
	pkill perl
	rm /var/run/webmin/miniserv.pid
	/usr/bin/perl /opt/webmin/miniserv.pl /etc/webmin/miniserv.conf
fi
prev_username=$(cat /opt/user.name)
sed -i "s/$prev_username:/${GUI_USER}:/g" /etc/webmin/miniserv.users
sed -i "s/$prev_username:/${GUI_USER}:/g" /etc/webmin/webmin.acl
sed -i "s/$prev_username/${GUI_USER}/g" /opt/user.name
/opt/webmin/changepass.pl /etc/webmin ${GUI_USER} ${GUI_PASSWORD} > /dev/null
if [ "${IPV6}" == "enable" ]; then sed -i "s/named -4 -c/named -c/g" /etc/supervisord.conf; fi
if [ "${IPV6}" == "disable" ]; then sed -i "s/named -c/named -4 -c/g" /etc/supervisord.conf; fi
/usr/bin/supervisord -n -c /etc/supervisord.conf
